version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
      - /myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
  webpacker:
    build: .
    command: bash -c 'rm -rf public/packs/* || true && bin/webpack-dev-server'
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules
      - public-data:/myapp/public
    ports:
      - '3035:3035'
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
volumes:
  node_modules:
  public-data:
  tmp-data:
  log-data:
